apiVersion: apps/v1
kind: Deployment
metadata:
  name: webby
spec:
  minReadySeconds: 5
  replicas: 3
  template:
    metadata:
      labels:
        name: webby
    spec:
      containers:
      - name: webby
        image: ghcr.io/undeadops/webby:latest
        command: ["webby"]
        ports:
        - containerPort: 5000
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 2
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 6
          successThreshold: 2
          timeoutSeconds: 1
      terminationGracePeriodSeconds: 45
