apiVersion: apps/v1
kind: Deployment
metadata:
  name: webby
spec:
  minReadySeconds: 5
  replicas: 3
  template:
    metadata:
      labels:
        name: webby
    spec:
      containers:
      - name: webby
        image: ghcr.io/undeadops/webby:latest
        ports:
        - containerPort: 5000
