apiVersion: apps/v1
kind: Deployment
metadata:
  name: webby
  labels:
    app: webby
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: webby
  template:
    metadata:
      labels:
        app: webby
    spec:
      containers:
      - name: webby
        image: ghcr.io/undeadops/webby:main-b7ef09
        command: ["webby"]
        args:
          - -delay
        ports:
        - containerPort: 5000
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 6
          successThreshold: 1
          timeoutSeconds: 1
      terminationGracePeriodSeconds: 45
