version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASS
         GIT_SHORT="$(echo ${CIRCLE_SHA1} | cut -c -7)"
         #ECR_LOGIN="$(aws ecr get-login --no-include-email --region ${AWS_REGION})"
         #${ECR_LOGIN} 
         #docker build -t "${ECR_ENDPOINT}/webby:${CIRCLE_BRANCH}-${GIT_SHORT}" .
         #docker push "${ECR_ENDPOINT}/webby:${CIRCLE_BRANCH}-${GIT_SHORT}"
         docker build -t "undeadops/webby:${CIRCLE_BRANCH}-${GIT_SHORT}" .
         docker push "undeadops/webby:${CIRCLE_BRANCH}-${GIT_SHORT}"
