version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASS

     # build the application image
     - run: docker build -t undeadops/webby:$CIRCLE_BRANCH-$(echo $CIRCLE_SHA1 | cut -c -7) .

     # deploy the image
     - run: docker push undeadops/webby:$CIRCLE_BRANCH-$(echo $CIRCLE_SHA1 | cut -c -7)
