version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
       #- run: |
       #  docker login -u $DOCKER_USER -p $DOCKER_PASS
     - run: |
         ECR_LOGIN=`aws ecr get-login --no-include-email --region $EC2_REGION` \
         ${ECR_LOGIN}

     # build the application image
     - run: docker build -t $(AWS_ACCT).dkr.ecr.us-east-2.amazonaws.com/webby:$CIRCLE_BRANCH-$(echo $CIRCLE_SHA1 | cut -c -7) .

     # deploy the image
     - run: docker push $(AWS_ACCT).dkr.ecr.us-east-2.amazonaws.com/webby:$CIRCLE_BRANCH-$(echo $CIRCLE_SHA1 | cut -c -7)
