name: Release

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: datetime
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d_%H:%M:%S')"
      -
        name: sha
        uses: benjlevesque/short-sha@v2.1
        id: short-sha
        with:
          length: 6
      - uses: actions/checkoutv3
      -
        name: Build and push
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: undeadops/webby
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          platforms: linux/amd64,linux/arm64
          buildargs: "BUILD_TIME=${{ steps.date.outputs.name }},COMMIT=${{ steps.short-sha.outputs.sha }},RELEASE=main-${{steps.short-sha.outputs.sha}}"
          tags: "main-${{ steps.outputs.release-version }}"

